name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - name: Publish package
        run: mvn --batch-mode deploy -Dmaven.test.skip=true 
        env:
          GITHUB_TOKEN: ${{ secrets.MAVEN_TOKEN }}
